title: "Shivani Devaraj"
description: "Data Science and Business Intelligence Portfolio"
email: "shivanidevaraj@example.com"
url: "https://shivanidevaraj.github.io" # base GitHub Pages URL
baseurl: "/shivani-portfolio" # if deploying under a subdirectory, else ""

# Freelancer Jekyll theme as a remote theme
remote_theme: jeromelachaud/freelancer-theme

# Social links (optional)
author:
  name: "Shivani Devaraj"

plugins:
  - jekyll-remote-theme

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Site Settings
show_downloads: false

# Portfolio Data (this references _data/projects.yml)
collections:
  portfolio:
    output: true
